package com.java1234.chap04.sec04;

import javax.management.RuntimeErrorException;

public class Demo1 {

	/**
	 * RuntimeException最好也用try。。catch捕获
	 * 运行时异常，编译时不检查，可以不使用try..catch捕获
	 * @throws RuntimeException
	 */
	public static void testRuntimeException() throws RuntimeException {
		throw new RuntimeException( "运行时异常");
	}
	
	public static void testException() throws Exception {
		throw new Exception("Exception异常");
	}
	
	public static void main(String[] args) {
		
		try {
			testRuntimeException();

		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
		}
		
		
		try {
			testException();
		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
		}
		
	}
	
	
	
}
